### PR TITLE
Fix citizens travelling to nether.

### LINKED ISSUE #90: Pathfinding in the nether eats memory
### Minecolonies version
v472
### Expected behavior
Nether pathfinding should recongnize that there is no way to home
### Actual behaviour
The citizen wanders of and eats gigs of ram till the server crashes
### Steps to reproduce the problem
Push a citizen in the nether

### PR DESCRIPTION
**Pull request by Raycoms**
Fixes #90  .

# Changes proposed in this pull request:
- Citizens won't travel through portals anymore.

Review please @Minecolonies/maintainers

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: I'd say!

**Comment by Kostronor** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/92/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by cltnschlosser** [comment]
@Kostronor Can you check the failed sonar thing.

**Comment by Kostronor** [comment]
Happens sometimes, we just have to run it again

**Pull request merged**
