### PR TITLE
Create .pullapprove.yml

### PR DESCRIPTION
**Pull request by Kostronor**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Minecolonies/minecolonies/pull/22" target="_blank">ReviewNinja

**Comment by Kostronor** [comment]
Approved

**Comment by cltnschlosser** [comment]
:shipit: Curious what this is

**Comment by cltnschlosser** [comment]
Approved

**Comment by Raycoms** [comment]
Approved  by me

**Pull request merged**
