### PR TITLE
Update PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by cltnschlosser**
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

Now that we have daily emails from pull review, we don't need to be tagged in this. It will prevent me from getting all the sonar emails :) We can tag each other or `@Minecolonies/maintainers` if needed.

### CODE REVIEW

**Comment by Kostronor** [comment]
Why delete the ping?

**Comment by Kostronor** [comment]
:shipit:

**Comment by cltnschlosser** [comment]
If I'm tagged in the PR description I will get an email for every single sonar comment. Where as if someone is needed and tagged in a comment, they should only get the email for the comment (assuming a similar email notification setup as me) @Kostronor

**Comment by Raycoms** [comment]
:shipit:

**Pull request merged**
